version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            set -x
            echo $PWD
            make deps
            docker run --rm gliderlabs/glu | tar xC /home/circleci/bin
            glu circleci
            glu container up
            glu build linux,darwin ./cmd
      - run: make test
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
