version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/sigil
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install lxc lxc1
            make deps
      - run:
          name: build
          command: |
            glu circleci
            glu container up
            CIRCLECI=false make build
      - store_artifacts:
          path: /home/circleci/sigil/build
      - run:
          name: test
          command: |
            make test
      - run:
          name: release
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
