version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/sigil
    steps:
      - checkout
      - run:
          name: update go
          command: |
            curl --silent https://dl.google.com/go/go1.13.8.linux-amd64.tar.gz -o /tmp/go1.13.8.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf /tmp/go1.13.8.linux-amd64.tar.gz
      - run:
          name: go version
          command: |
            go version
            which go
            echo $PATH
      - run:
          name: install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install lxc lxc1
            make deps
      - run:
          name: build
          command: |
            glu circleci
            glu container up
            CIRCLECI=false make build
      - store_artifacts:
          path: /home/circleci/sigil/build
      - run:
          name: test
          command: |
            make test
      - run:
          name: release
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
