version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/sigil
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install lxc lxc1
      - run:
          command: |
            set -x
            make deps
            docker run --rm gliderlabs/glu | tar xC /home/circleci/bin
            glu circleci
            glu container up
            CIRCLECI=false glu build linux,darwin ./cmd
      - run: make test
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
