version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            set -x
            go version
            sudo add-apt-repository ppa:longsleep/golang-backports
            sudo apt update
            sudo apt install golang-go
            go version
            make deps
            docker run --rm gliderlabs/glu | tar xC /home/ubuntu/bin
            glu circleci
            glu container up
            glu build linux,darwin ./cmd
      - run: make test
      - run:
          command: |
            if [[ "$CIRCLE_BRANCH" == "release" ]]; then
              make release
            fi
